### ISSUE TITLE
Errorコメント"Failed to create pcap session: couldn't find devices to listen on."

### ISSUE THREAD

**Issue by rkikurin** [KASA12/twitterBotOnRaspberryPi#1]
READMEの6番の段階で、下記のエラーが出ています。
Nodejsのバージョンなどは、apt-get installで直接入ったものをそのまま使っているので、v4.8.2が入っているので、その問題な可能性がありますが。

```
[Error: socket: Operation not permitted]
Failed to create pcap session: couldn't find devices to listen on.
Try running with elevated privileges via 'sudo'
/home/pi/app/twitterBotOnRaspberryPi/node_modules/node-dash-button/index.js:28
        throw new Error('Error: No devices to listen');
        ^

Error: Error: No devices to listen
    at create_session (/home/pi/app/twitterBotOnRaspberryPi/node_modules/node-dash-button/index.js:28:15)
    at register (/home/pi/app/twitterBotOnRaspberryPi/node_modules/node-dash-button/index.js:47:24)
    at dashButton (/home/pi/app/twitterBotOnRaspberryPi/dashButton.js:3:16)
    at Object.<anonymous> (/home/pi/app/twitterBotOnRaspberryPi/main.js:10:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
```

**Comment by KASA12** [comment]
@rkikurin `sudo node main.js`を試してみてください。

**Comment by rkikurin** [comment]
解決しました、sudo権限だけの問題でした。ありがとうございます。
